name: Continuous Integration

on:
  push:
    branches:
      - v13
  pull_request:
    branches:
      - v13

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          package-manager-cache: false

      - name: Cache
        id: cache
        uses: actions/cache@v5
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Clean Install
        run: npm clean-install

      - name: Build/ESLint
        run: npx tsc --noEmit && npm run eslint
